<a href="https://colab.research.google.com/github/benram2004-lab/mis433/blob/main/IMDB_manipulation_summarization_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [1]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data Folder /imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [4]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [5]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [6]:
# Display top 10 movies' title, released year and IMDB rating.
print(imdb.loc[:9, ['Series_Title', 'Released_Year', 'IMDB_Rating']])

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [7]:
# Display movies ranked 11-20.
# Show their title, released year and IMDB rating.
print(imdb.loc[10:19, ['Series_Title', 'Released_Year', 'IMDB_Rating']])

                                         Series_Title Released_Year  \
10  The Lord of the Rings: The Fellowship of the Ring          2001
11                                       Forrest Gump          1994
12                    Il buono, il brutto, il cattivo          1966
13              The Lord of the Rings: The Two Towers          2002
14                                         The Matrix          1999
15                                         Goodfellas          1990
16     Star Wars: Episode V - The Empire Strikes Back          1980
17                    One Flew Over the Cuckoo's Nest          1975
18                                           Hamilton          2020
19                                       Gisaengchung          2019

    IMDB_Rating
10          8.8
11          8.8
12          8.8
13          8.7
14          8.7
15          8.7
16          8.7
17          8.7
18          8.6
19          8.6

In [8]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
print(imdb.loc[imdb['Director'] == 'Quentin Tarantino', ['Series_Title', 'Released_Year', 'IMDB_Rating', 'Gross']])

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [9]:
print(imdb.loc[(imdb['Certificate'] == 'R') & (imdb['IMDB_Rating'] >= 8.5), ['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']])

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [10]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
print=(imdb['Released_Year'].nunique())
print

100

In [11]:
# Count the number of movies in each "Released_Year"?
# Hint: value_counts()
print=(imdb['Released_Year'].value_counts())
print

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [12]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's is not.
# Find this movie.
print=(imdb.loc[~imdb['Released_Year'].str.isnumeric()])
print

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [13]:
del print
imdb.loc[966, 'Released_Year'] = '1995'
imdb.loc[966, 'Certificate'] = 'PG'
print(imdb.loc[966, ['Series_Title', 'Released_Year', 'Certificate']])

Series_Title     Apollo 13
Released_Year         1995
Certificate             PG
Name: 966, dtype: object

In [14]:
# Change the data type of 'Released_Year' to int
imdb.loc[:, 'Released_Year'] = imdb['Released_Year'].astype(int)

In [15]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
print(imdb.loc[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5), ['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']])

        Series_Title Released_Year Certificate  IMDB_Rating
8          Inception          2010          UA          8.8
18          Hamilton          2020       PG-13          8.6
19      Gisaengchung          2019           A          8.6
20   Soorarai Pottru          2020           U          8.6
21      Interstellar          2014          UA          8.6
33             Joker          2019           A          8.5
34          Whiplash          2014           A          8.5
35  The Intouchables          2011          UA          8.5

In [16]:
print(imdb.loc[imdb['Genre'].str.contains('Animation'), 'Series_Title'])

23         Sen to Chihiro no kamikakushi
43                         The Lion King
46                        Hotaru no haka
56                        Kimi no na wa.
58     Spider-Man: Into the Spider-Verse
                     ...
956                                Mulan
971                    Omohide poro poro
976                   The Little Mermaid
986                       Watership Down
992                      The Jungle Book
Name: Series_Title, Length: 82, dtype: object

In [17]:
print(imdb)

                                           Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...
..                                                 ...
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min
1               The Godfather          1972           A  175 min
2             The Dark Knight          2008          UA  152 min
3      The Godfather: Part II          1974           A  202 min
4                12 Angry Men          1957           U   96 min
..                        ...           ...         ...      ...
995    Breakfast at Tiffany's          1961           A  115 min
996                     Giant          1956           G  201 min
997     From Here to Eternity          1953      Passed  118 min
998                  Lifeboat          1944         NaN   97 min
999              The 39 Steps          1935         NaN   86 min

                        Genre  IMDB_Rating  \
0                       Drama          9.3
1                Crime, Drama          9.2
2        Action, Crime, Drama          9.0
3                Crime, Drama          9.0
4                Crime, Drama          9.0
..                        ...          ...
995    Comedy, Drama, Romance          7.6
996            Drama, Western          7.6
997       Drama, Romance, War          7.6
998                Drama, War          7.6
999  Crime, Mystery, Thriller          7.6

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0
1    An organized crime dynasty's aging patriarch t...       100.0
2    When the menace known as the Joker wreaks havo...        84.0
3    The early life and career of Vito Corleone in ...        90.0
4    A jury holdout attempts to prevent a miscarria...        96.0
..                                                 ...         ...
995  A young New York socialite becomes interested ...        76.0
996  Sprawling epic covering the life of a Texas ca...        84.0
997  In Hawaii in 1941, a private is cruelly punish...        85.0
998  Several survivors of a torpedoed merchant ship...        78.0
999  A man in London tries to help a counter-espion...        93.0

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman
1    Francis Ford Coppola      Marlon Brando          Al Pacino
2       Christopher Nolan     Christian Bale       Heath Ledger
3    Francis Ford Coppola          Al Pacino     Robert De Niro
4            Sidney Lumet        Henry Fonda        Lee J. Cobb
..                    ...                ...                ...
995         Blake Edwards     Audrey Hepburn     George Peppard
996        George Stevens   Elizabeth Taylor        Rock Hudson
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll

              Star3           Star4  No_of_Votes        Gross
0        Bob Gunton  William Sadler      2343110   28,341,469
1        James Caan    Diane Keaton      1620367  134,966,411
2     Aaron Eckhart   Michael Caine      2303232  534,858,444
3     Robert Duvall    Diane Keaton      1129952   57,300,000
4     Martin Balsam    John Fiedler       689845    4,360,000
..              ...             ...          ...          ...
995   Patricia Neal     Buddy Ebsen       166544          NaN
996      James Dean   Carroll Baker        34075          NaN
997    Deborah Kerr      Donna Reed        43374   30,500,000
998   Walter Slezak  William Bendix        26471          NaN
999  Lucie Mannheim  Godfrey Tearle        51853          NaN

[1000 rows x 16 columns]

In [18]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]

stars.head()

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

In [19]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
genres.head()

               Series_Title Released_Year                 Genre
0  The Shawshank Redemption          1994                 Drama
1             The Godfather          1972          Crime, Drama
2           The Dark Knight          2008  Action, Crime, Drama
3    The Godfather: Part II          1974          Crime, Drama
4              12 Angry Men          1957          Crime, Drama

In [20]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
sorted_genres = genres.sort_values(by='Released_Year')
sorted_genres.head()

                     Series_Title Released_Year                     Genre
321  Das Cabinet des Dr. Caligari          1920  Fantasy, Horror, Mystery
127                       The Kid          1921     Comedy, Drama, Family
568                     Nosferatu          1922           Fantasy, Horror
194                  Sherlock Jr.          1924   Action, Comedy, Romance
193                 The Gold Rush          1925  Adventure, Comedy, Drama

In [21]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
sorted_imdb = imdb.sort_values(by='Gross', ascending=False)
print(sorted_imdb.head()[['Series_Title', 'Released_Year', 'Certificate', 'Gross']])

           Series_Title Released_Year Certificate       Gross
738            Rockstar          2011          UA     985,912
682    The Color Purple          1985           U  98,467,863
194        Sherlock Jr.          1924      Passed     977,375
748  The Social Network          2010          UA  96,962,694
7      Schindler's List          1993           A  96,898,818

In [22]:
# Does the sorting result look right to you? What's the problem?
# answer: the gross is not descending in proper order

In [23]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

imdb['Gross'] = pd.to_numeric(imdb['Gross'].str.replace(',', '', regex=False), errors='coerce')

print("DataFrame Info after Gross conversion:")
imdb.info()
print("\nDataFrame Head after Gross conversion:")
display(imdb.head())

DataFrame Info after Gross conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    float64
dtypes: float64(3), int64(1), object(12)
memory usage: 125.1+ KB

DataFrame Head after Gross conversion:

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0

In [24]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"

filtered_and_sorted_movies = imdb.loc[
    (imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5),
    ['Series_Title', 'Released_Year', 'Certificate', 'Gross']
].sort_values(by='Gross', ascending=False)

display(filtered_and_sorted_movies)

        Series_Title Released_Year Certificate        Gross
33             Joker          2019           A  335451311.0
8          Inception          2010          UA  292576195.0
21      Interstellar          2014          UA  188020017.0
19      Gisaengchung          2019           A   53367844.0
35  The Intouchables          2011          UA   13182281.0
34          Whiplash          2014           A   13092000.0
18          Hamilton          2020       PG-13          NaN
20   Soorarai Pottru          2020           U          NaN

In [25]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

imdb['Runtime_min'] = imdb['Runtime'].str.replace(' min', '').astype(int)

display(imdb[['Series_Title', 'Runtime', 'Runtime_min']].head())

               Series_Title  Runtime  Runtime_min
0  The Shawshank Redemption  142 min          142
1             The Godfather  175 min          175
2           The Dark Knight  152 min          152
3    The Godfather: Part II  202 min          202
4              12 Angry Men   96 min           96

In [26]:
# Add a new column "Age_Year" by expression: Current year - Released_Year
import datetime
current_year = datetime.datetime.now().year
imdb['Age_Year'] = current_year - imdb['Released_Year']

# Display the head with the new column
display(imdb[['Series_Title', 'Released_Year', 'Age_Year']].head())

               Series_Title Released_Year Age_Year
0  The Shawshank Redemption          1994       32
1             The Godfather          1972       54
2           The Dark Knight          2008       18
3    The Godfather: Part II          1974       52
4              12 Angry Men          1957       69

In [27]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10

display(imdb[['Series_Title', 'Released_Year', 'Decade']].head())

               Series_Title Released_Year Decade
0  The Shawshank Redemption          1994   1990
1             The Godfather          1972   1970
2           The Dark Knight          2008   2000
3    The Godfather: Part II          1974   1970
4              12 Angry Men          1957   1950

## Part 2: Data Summarization

In [28]:
# Total "Gross" of all top 1000 movies
print(imdb['Gross'].sum())

56536877976.0

In [29]:
# Average "No_of_Votes" of all movies
average_votes = imdb['No_of_Votes'].mean()
print(average_votes)

273692.911

In [30]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order

print("\nNumber of movies per decade (sorted by count descending):")
display(imdb['Decade'].value_counts())

Number of movies per decade (sorted by count descending):

Decade
2010    242
2000    237
1990    151
1980     89
1970     76
1960     73
1950     56
1940     35
1930     24
1920     11
2020      6
Name: count, dtype: int64

In [31]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
display(imdb['Director'].value_counts().head(10))

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [32]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
display(imdb.groupby('Director').agg(number_of_movies=('Series_Title', 'count'),
average_imdb_rating=('IMDB_Rating', 'mean'),
total_gross=('Gross', 'sum')).sort_values(by='total_gross', ascending=False).head(10))

                   number_of_movies  average_imdb_rating   total_gross
Director
Steven Spielberg                 13             8.030769  2.478133e+09
Anthony Russo                     4             8.075000  2.205039e+09
Christopher Nolan                 8             8.462500  1.937454e+09
James Cameron                     5             8.080000  1.748237e+09
Peter Jackson                     5             8.400000  1.597312e+09
J.J. Abrams                       3             7.833333  1.423171e+09
Brad Bird                         4             7.900000  1.099628e+09
Robert Zemeckis                   5             8.120000  1.049446e+09
David Yates                       3             7.800000  9.789537e+08
Pete Docter                       4             8.125000  9.393821e+08

In [33]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count

decade_director_summary = imdb.groupby(['Decade', 'Director']).agg(
    number_of_movies=('Series_Title', 'count'),
    average_imdb_rating=('IMDB_Rating', 'mean')
).sort_values(by='number_of_movies', ascending=False)

display(decade_director_summary.head(10))

                          number_of_movies  average_imdb_rating
Decade Director
1950   Billy Wilder                      6             8.133333
       Akira Kurosawa                    5             8.260000
2010   Denis Villeneuve                  5             7.980000
1950   Alfred Hitchcock                  5             8.220000
1980   Steven Spielberg                  5             7.980000
1940   Alfred Hitchcock                  5             7.880000
2000   Clint Eastwood                    5             7.940000
       Christopher Nolan                 4             8.525000
1960   Sergio Leone                      4             8.400000
1990   Joel Coen                         4             7.900000

In [34]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.

#group by director
decade_counts_per_director = imdb.groupby(['Director', 'Decade']).size().reset_index(name='number_of_movies')

# Filter
multi_decade_directors = decade_counts_per_director.groupby('Director').filter(lambda x: x['Decade'].nunique() >= 5)


display(multi_decade_directors.sort_values(by=['Director', 'Decade']))

             Director  Decade  number_of_movies
247    Hayao Miyazaki    1970                 1
248    Hayao Miyazaki    1980                 4
249    Hayao Miyazaki    1990                 2
250    Hayao Miyazaki    2000                 3
251    Hayao Miyazaki    2010                 1
424   Martin Scorsese    1970                 1
425   Martin Scorsese    1980                 3
426   Martin Scorsese    1990                 2
427   Martin Scorsese    2000                 1
428   Martin Scorsese    2010                 3
644  Steven Spielberg    1970                 2
645  Steven Spielberg    1980                 5
646  Steven Spielberg    1990                 3
647  Steven Spielberg    2000                 2
648  Steven Spielberg    2010                 1

In [35]:
# Question 1: top ten highest grossing movies and the amount of gross

highest_grossing = imdb.sort_values(by='Gross', ascending=False).head(10)
display(highest_grossing[['Series_Title', 'Gross']])

                                   Series_Title        Gross
477  Star Wars: Episode VII - The Force Awakens  936662225.0
59                            Avengers: Endgame  858373000.0
623                                      Avatar  760507625.0
60                       Avengers: Infinity War  678815482.0
652                                     Titanic  659325379.0
357                                The Avengers  623279547.0
891                               Incredibles 2  608581744.0
2                               The Dark Knight  534858444.0
582                                   Rogue One  532177324.0
63                        The Dark Knight Rises  448139099.0

In [36]:
# Questions 2: highest grossing movie per decade, #result will include decade, director, and gross

highest_grossing_per_decade = imdb.dropna(subset=['Gross']).loc[imdb.dropna(subset=['Gross']).groupby('Decade')['Gross'].idxmax()]
display(highest_grossing_per_decade[['Decade', 'Series_Title', 'Director', 'Gross']])

,Decade,Series_Title,Director,Gross
127,1920,The Kid,Charles Chaplin,5450000.0
314,1930,Gone with the Wind,Victor Fleming,198676459.0
875,1940,Fantasia,James Algar,76408097.0
552,1950,The Ten Commandments,Cecil B. DeMille,93740000.0
429,1960,The Sound of Music,Robert Wise,163214286.0
29,1970,Star Wars,George Lucas,322740140.0
688,1980,E.T. the Extra-Terrestrial,Steven Spielberg,435110554.0
652,1990,Titanic,James Cameron,659325379.0
623,2000,Avatar,James Cameron,760507625.0
477,2010,Star Wars: Episode VII - The Force Awakens,J.J. Abrams,936662225.0