<a href="https://colab.research.google.com/github/benram2004-lab/mis433/blob/main/Week_2_assignment_data_manipuation_flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [32]:
import pandas as pd

In [33]:
# Install the package 'nycflights13' before you can run this
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,air_time,distance,hour,minute,time_hour,dep_time_minutes,sched_dep_time_minutes,arr_time_minutes,calculated_flight_time,calculated_dep_delay
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,227.0,1400,5,15,2013-01-01T10:00:00Z,317.0,315.0,510.0,193.0,2.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,227.0,1416,5,29,2013-01-01T10:00:00Z,333.0,329.0,530.0,197.0,4.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,160.0,1089,5,40,2013-01-01T10:00:00Z,342.0,340.0,563.0,221.0,2.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,183.0,1576,5,45,2013-01-01T10:00:00Z,344.0,345.0,604.0,260.0,-1.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,116.0,762,6,0,2013-01-01T11:00:00Z,354.0,360.0,492.0,138.0,-6.0

In [34]:
pip install nycflights13

Requirement already satisfied: nycflights13 in /usr/local/lib/python3.12/dist-packages (0.0.3)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)

After installing, please run the cell that produced the error again.

In [35]:
flights.shape

(336776, 24)

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [36]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,air_time,distance,hour,minute,time_hour,dep_time_minutes,sched_dep_time_minutes,arr_time_minutes,calculated_flight_time,calculated_dep_delay
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,...,327346.000000,336776.000000,336776.000000,336776.000000,336776,328521.000000,336776.000000,328063.000000,328063.000000,328521.00000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,...,NaN,NaN,NaN,NaN,6936,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,...,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,...,NaN,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,NaN
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,...,150.686460,1039.912604,13.180247,26.230100,NaN,822.168169,817.044944,913.020819,91.004356,7.34845
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,...,93.688305,733.233033,4.661316,19.300846,NaN,292.730990,281.147222,320.172755,253.830350,86.99798
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,...,20.000000,17.000000,1.000000,0.000000,NaN,1.000000,66.000000,1.000000,-1401.000000,-1438.00000
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,...,82.000000,502.000000,9.000000,8.000000,NaN,547.000000,546.000000,664.000000,91.000000,-5.00000
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,...,129.000000,872.000000,13.000000,29.000000,NaN,841.000000,839.000000,935.000000,133.000000,-2.00000
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,...,192.000000,1389.000000,17.000000,44.000000,NaN,1064.000000,1049.000000,1180.000000,172.000000,10.00000
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,...,695.000000,4983.000000,23.000000,59.000000,NaN,1440.000000,1439.000000,1440.000000,690.000000,911.00000

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [37]:
# Had an arrival delay of two or more hours
print(flights[flights['arr_delay'] >= 120])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
119     2013      1    1     811.0             630      101.0    1047.0
151     2013      1    1     848.0            1835      853.0    1001.0
218     2013      1    1     957.0             733      144.0    1056.0
268     2013      1    1    1114.0             900      134.0    1447.0
447     2013      1    1    1505.0            1310      115.0    1638.0
...      ...    ...  ...       ...             ...        ...       ...
336579  2013      9   30    1823.0            1545      158.0    1934.0
336668  2013      9   30    1951.0            1649      182.0    2157.0
336724  2013      9   30    2053.0            1815      158.0    2310.0
336757  2013      9   30    2159.0            1845      194.0    2344.0
336763  2013      9   30    2235.0            2001      154.0      59.0

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
119                830      137.0      MQ  ...     118.0      544    6     30
151               1950      851.0      MQ  ...      41.0      184   18     35
218                853      123.0      UA  ...      37.0      200    7     33
268               1222      145.0      UA  ...     248.0     1416    9      0
447               1431      127.0      EV  ...      63.0      277   13     10
...                ...        ...     ...  ...       ...      ...  ...    ...
336579            1733      121.0      9E  ...      95.0      765   15     45
336668            1903      174.0      EV  ...      95.0      708   16     49
336724            2054      136.0      EV  ...      91.0      746   18     15
336757            2030      194.0      9E  ...      50.0      301   18     45
336763            2249      130.0      B6  ...     123.0      944   20      1

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
119     2013-01-01T11:00:00Z             491.0                   390.0
151     2013-01-01T23:00:00Z             528.0                  1115.0
218     2013-01-01T12:00:00Z             597.0                   453.0
268     2013-01-01T14:00:00Z             674.0                   540.0
447     2013-01-01T18:00:00Z             905.0                   790.0
...                      ...               ...                     ...
336579  2013-09-30T19:00:00Z            1103.0                   945.0
336668  2013-09-30T20:00:00Z            1191.0                  1009.0
336724  2013-09-30T22:00:00Z            1253.0                  1095.0
336757  2013-09-30T22:00:00Z            1319.0                  1125.0
336763  2013-10-01T00:00:00Z            1355.0                  1201.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
119                647.0                  156.0                 101.0
151                601.0                   73.0                -587.0
218                656.0                   59.0                 144.0
268                887.0                  213.0                 134.0
447                998.0                   93.0                 115.0
...                  ...                    ...                   ...
336579            1174.0                   71.0                 158.0
336668            1317.0                  126.0                 182.0
336724            1390.0                  137.0                 158.0
336757            1424.0                  105.0                 194.0
336763              59.0                -1296.0                 154.0

[10200 rows x 24 columns]

In [38]:
# Flew to Houston (IAH or HOU)
print(flights[(flights['dest'] == 'IAH') | (flights['dest'] == 'HOU')])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0
1       2013      1    1     533.0             529        4.0     850.0
32      2013      1    1     623.0             627       -4.0     933.0
81      2013      1    1     728.0             732       -4.0    1041.0
89      2013      1    1     739.0             739        0.0    1104.0
...      ...    ...  ...       ...             ...        ...       ...
336524  2013      9   30    1729.0            1720        9.0    2001.0
336527  2013      9   30    1735.0            1715       20.0    2010.0
336618  2013      9   30    1859.0            1859        0.0    2134.0
336694  2013      9   30    2015.0            2015        0.0    2244.0
336737  2013      9   30    2105.0            2106       -1.0    2329.0

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
0                  819       11.0      UA  ...     227.0     1400    5     15
1                  830       20.0      UA  ...     227.0     1416    5     29
32                 932        1.0      UA  ...     229.0     1416    6     27
81                1038        3.0      UA  ...     238.0     1416    7     32
89                1038       26.0      UA  ...     249.0     1400    7     39
...                ...        ...     ...  ...       ...      ...  ...    ...
336524            2010       -9.0      UA  ...     173.0     1400   17     20
336527            2005        5.0      WN  ...     188.0     1411   17     15
336618            2159      -25.0      UA  ...     180.0     1416   18     59
336694            2307      -23.0      UA  ...     174.0     1400   20     15
336737            2354      -25.0      UA  ...     175.0     1400   21      6

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
0       2013-01-01T10:00:00Z             317.0                   315.0
1       2013-01-01T10:00:00Z             333.0                   329.0
32      2013-01-01T11:00:00Z             383.0                   387.0
81      2013-01-01T12:00:00Z             448.0                   452.0
89      2013-01-01T12:00:00Z             459.0                   459.0
...                      ...               ...                     ...
336524  2013-09-30T21:00:00Z            1049.0                  1040.0
336527  2013-09-30T21:00:00Z            1055.0                  1035.0
336618  2013-09-30T22:00:00Z            1139.0                  1139.0
336694  2013-10-01T00:00:00Z            1215.0                  1215.0
336737  2013-10-01T01:00:00Z            1265.0                  1266.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
0                  510.0                  193.0                   2.0
1                  530.0                  197.0                   4.0
32                 573.0                  190.0                  -4.0
81                 641.0                  193.0                  -4.0
89                 664.0                  205.0                   0.0
...                  ...                    ...                   ...
336524            1201.0                  152.0                   9.0
336527            1210.0                  155.0                  20.0
336618            1294.0                  155.0                   0.0
336694            1364.0                  149.0                   0.0
336737            1409.0                  144.0                  -1.0

[9313 rows x 24 columns]

In [39]:
# Were operated by United (UA), American (AA), or Delta (DL)
print(flights[(flights['carrier'] == 'UA') | (flights['carrier'] == 'AA') | (flights['carrier'] == 'DL')])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0
1       2013      1    1     533.0             529        4.0     850.0
2       2013      1    1     542.0             540        2.0     923.0
4       2013      1    1     554.0             600       -6.0     812.0
5       2013      1    1     554.0             558       -4.0     740.0
...      ...    ...  ...       ...             ...        ...       ...
336737  2013      9   30    2105.0            2106       -1.0    2329.0
336744  2013      9   30    2121.0            2100       21.0    2349.0
336751  2013      9   30    2140.0            2140        0.0      10.0
336755  2013      9   30    2149.0            2156       -7.0    2245.0
336762  2013      9   30    2233.0            2113       80.0     112.0

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
0                  819       11.0      UA  ...     227.0     1400    5     15
1                  830       20.0      UA  ...     227.0     1416    5     29
2                  850       33.0      AA  ...     160.0     1089    5     40
4                  837      -25.0      DL  ...     116.0      762    6      0
5                  728       12.0      UA  ...     150.0      719    5     58
...                ...        ...     ...  ...       ...      ...  ...    ...
336737            2354      -25.0      UA  ...     175.0     1400   21      6
336744              14      -25.0      DL  ...     296.0     2475   21      0
336751              40      -30.0      AA  ...     298.0     2475   21     40
336755            2308      -23.0      UA  ...      37.0      200   21     56
336762              30       42.0      UA  ...     318.0     2565   21     13

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
0       2013-01-01T10:00:00Z             317.0                   315.0
1       2013-01-01T10:00:00Z             333.0                   329.0
2       2013-01-01T10:00:00Z             342.0                   340.0
4       2013-01-01T11:00:00Z             354.0                   360.0
5       2013-01-01T10:00:00Z             354.0                   358.0
...                      ...               ...                     ...
336737  2013-10-01T01:00:00Z            1265.0                  1266.0
336744  2013-10-01T01:00:00Z            1281.0                  1260.0
336751  2013-10-01T01:00:00Z            1300.0                  1300.0
336755  2013-10-01T01:00:00Z            1309.0                  1316.0
336762  2013-10-01T01:00:00Z            1353.0                  1273.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
0                  510.0                  193.0                   2.0
1                  530.0                  197.0                   4.0
2                  563.0                  221.0                   2.0
4                  492.0                  138.0                  -6.0
5                  460.0                  106.0                  -4.0
...                  ...                    ...                   ...
336737            1409.0                  144.0                  -1.0
336744            1429.0                  148.0                  21.0
336751              10.0                -1290.0                   0.0
336755            1365.0                   56.0                  -7.0
336762              72.0                -1281.0                  80.0

[139504 rows x 24 columns]

In [40]:
# Departed in July, August, and September
print(flights[(flights['month'] == 7) | (flights['month'] == 8) | (flights['month'] == 9)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
250450  2013      7    1       1.0            2029      212.0     236.0
250451  2013      7    1       2.0            2359        3.0     344.0
250452  2013      7    1      29.0            2245      104.0     151.0
250453  2013      7    1      43.0            2130      193.0     322.0
250454  2013      7    1      44.0            2150      174.0     300.0
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
250450            2359      157.0      B6  ...     315.0     2586   20     29
250451             344        0.0      B6  ...     200.0     1598   23     59
250452               1      110.0      B6  ...      66.0      266   22     45
250453              14      188.0      B6  ...     143.0     1076   21     30
250454             100      120.0      AA  ...     297.0     2475   21     50
...                ...        ...     ...  ...       ...      ...  ...    ...
336771            1634        NaN      9E  ...       NaN      213   14     55
336772            2312        NaN      9E  ...       NaN      198   22      0
336773            1330        NaN      MQ  ...       NaN      764   12     10
336774            1344        NaN      MQ  ...       NaN      419   11     59
336775            1020        NaN      MQ  ...       NaN      431    8     40

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
250450  2013-07-02T00:00:00Z               1.0                  1229.0
250451  2013-07-02T03:00:00Z               2.0                  1439.0
250452  2013-07-02T02:00:00Z              29.0                  1365.0
250453  2013-07-02T01:00:00Z              43.0                  1290.0
250454  2013-07-02T01:00:00Z              44.0                  1310.0
...                      ...               ...                     ...
336771  2013-09-30T18:00:00Z               NaN                   895.0
336772  2013-10-01T02:00:00Z               NaN                  1320.0
336773  2013-09-30T16:00:00Z               NaN                   730.0
336774  2013-09-30T15:00:00Z               NaN                   719.0
336775  2013-09-30T12:00:00Z               NaN                   520.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
250450             156.0                  155.0               -1228.0
250451             224.0                  222.0               -1437.0
250452             111.0                   82.0               -1336.0
250453             202.0                  159.0               -1247.0
250454             180.0                  136.0               -1266.0
...                  ...                    ...                   ...
336771               NaN                    NaN                   NaN
336772               NaN                    NaN                   NaN
336773               NaN                    NaN                   NaN
336774               NaN                    NaN                   NaN
336775               NaN                    NaN                   NaN

[86326 rows x 24 columns]

In [41]:
# Arrived more than two hours late, but didn’t leave late
print(flights[(flights['arr_delay'] > 120) & (flights['dep_delay'] <= 0)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
22911   2013      1   27    1419.0            1420       -1.0    1754.0
33011   2013     10    7    1350.0            1350        0.0    1736.0
33019   2013     10    7    1357.0            1359       -2.0    1858.0
41075   2013     10   16     657.0             700       -3.0    1258.0
55985   2013     11    1     658.0             700       -2.0    1329.0
152766  2013      3   18    1844.0            1847       -3.0      39.0
180893  2013      4   17    1635.0            1640       -5.0    2049.0
181270  2013      4   18     558.0             600       -2.0    1149.0
181327  2013      4   18     655.0             700       -5.0    1213.0
213693  2013      5   22    1827.0            1830       -3.0    2217.0
214512  2013      5   23    1810.0            1810        0.0    2208.0
226434  2013      6    5    1604.0            1615      -11.0    2041.0
235033  2013      6   14    1708.0            1710       -2.0    2227.0
244329  2013      6   24    1602.0            1605       -3.0    2134.0
247568  2013      6   27    2052.0            2100       -8.0      13.0
249957  2013      6   30    1423.0            1425       -2.0    1816.0
250689  2013      7    1     905.0             905        0.0    1443.0
256340  2013      7    7    1659.0            1700       -1.0    2050.0
256358  2013      7    7    1727.0            1730       -3.0    2203.0
256373  2013      7    7    1746.0            1755       -9.0    2133.0
256405  2013      7    7    1823.0            1830       -7.0    2201.0
270742  2013      7   22    1555.0            1600       -5.0    2139.0
270752  2013      7   22    1606.0            1615       -9.0    2056.0
270762  2013      7   22    1628.0            1630       -2.0    2151.0
276564  2013      7   28    1710.0            1711       -1.0    2248.0
287148  2013      8    8    1457.0            1500       -3.0    1828.0
291439  2013      8   13     657.0             659       -2.0    1015.0
305985  2013      8   28    1157.0            1200       -3.0    1520.0
325764  2013      9   19     656.0             700       -4.0    1037.0

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
22911             1550      124.0      MQ  ...     135.0      719   14     20
33011             1526      130.0      EV  ...     117.0      812   13     50
33019             1654      124.0      AA  ...     192.0     1389   13     59
41075             1056      122.0      B6  ...     225.0     1598    7      0
55985             1015      194.0      VX  ...     336.0     2475    7      0
152766            2219      140.0      UA  ...     386.0     2586   18     47
180893            1845      124.0      MQ  ...     130.0      502   16     40
181270             850      179.0      AA  ...     234.0     1389    6      0
181327             950      143.0      AA  ...     230.0     1372    7      0
213693            2010      127.0      MQ  ...      90.0      419   18     30
214512            2000      128.0      MQ  ...      82.0      479   18     10
226434            1840      121.0      MQ  ...     158.0      762   16     15
235033            2015      132.0      AA  ...     334.0     2475   17     10
244329            1916      138.0      DL  ...     247.0     1521   16      5
247568            2210      123.0      US  ...      46.0      184   21      0
249957            1554      142.0      B6  ...      80.0      301   14     25
250689            1223      140.0      DL  ...     183.0     1096    9      5
256340            1823      147.0      US  ...      64.0      214   17      0
256358            1951      132.0      F9  ...     236.0     1620   17     30
256373            1921      132.0      B6  ...      78.0      228   17     55
256405            1955      126.0      MQ  ...     113.0      764   18     30
270742            1938      121.0      DL  ...     371.0     2586   16      0
270752            1831      145.0      DL  ...     140.0     1020   16     15
270762            1939      132.0      B6  ...     332.0     2475   16     30
276564            2039      129.0      B6  ...     353.0     2576   17     11
287148            1624      124.0      US  ...      70.0      214   15      0
291439             814      121.0      EV  ...     146.0      748    6     59
305985            1316      124.0      US  ...      63.0      214   12      0
325764             833      124.0      UA  ...     192.0      733    7      0

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
22911   2013-01-27T19:00:00Z             859.0                   860.0
33011   2013-10-07T17:00:00Z             830.0                   830.0
33019   2013-10-07T17:00:00Z             837.0                   839.0
41075   2013-10-16T11:00:00Z             417.0                   420.0
55985   2013-11-01T11:00:00Z             418.0                   420.0
152766  2013-03-18T22:00:00Z            1124.0                  1127.0
180893  2013-04-17T20:00:00Z             995.0                  1000.0
181270  2013-04-18T10:00:00Z             358.0                   360.0
181327  2013-04-18T11:00:00Z             415.0                   420.0
213693  2013-05-22T22:00:00Z            1107.0                  1110.0
214512  2013-05-23T22:00:00Z            1090.0                  1090.0
226434  2013-06-05T20:00:00Z             964.0                   975.0
235033  2013-06-14T21:00:00Z            1028.0                  1030.0
244329  2013-06-24T20:00:00Z             962.0                   965.0
247568  2013-06-28T01:00:00Z            1252.0                  1260.0
249957  2013-06-30T18:00:00Z             863.0                   865.0
250689  2013-07-01T13:00:00Z             545.0                   545.0
256340  2013-07-07T21:00:00Z            1019.0                  1020.0
256358  2013-07-07T21:00:00Z            1047.0                  1050.0
256373  2013-07-07T21:00:00Z            1066.0                  1075.0
256405  2013-07-07T22:00:00Z            1103.0                  1110.0
270742  2013-07-22T20:00:00Z             955.0                   960.0
270752  2013-07-22T20:00:00Z             966.0                   975.0
270762  2013-07-22T20:00:00Z             988.0                   990.0
276564  2013-07-28T21:00:00Z            1030.0                  1031.0
287148  2013-08-08T19:00:00Z             897.0                   900.0
291439  2013-08-13T10:00:00Z             417.0                   419.0
305985  2013-08-28T16:00:00Z             717.0                   720.0
325764  2013-09-19T11:00:00Z             416.0                   420.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
22911             1074.0                  215.0                  -1.0
33011             1056.0                  226.0                   0.0
33019             1138.0                  301.0                  -2.0
41075              778.0                  361.0                  -3.0
55985              809.0                  391.0                  -2.0
152766              39.0                -1085.0                  -3.0
180893            1249.0                  254.0                  -5.0
181270             709.0                  351.0                  -2.0
181327             733.0                  318.0                  -5.0
213693            1337.0                  230.0                  -3.0
214512            1328.0                  238.0                   0.0
226434            1241.0                  277.0                 -11.0
235033            1347.0                  319.0                  -2.0
244329            1294.0                  332.0                  -3.0
247568              13.0                -1239.0                  -8.0
249957            1096.0                  233.0                  -2.0
250689             883.0                  338.0                   0.0
256340            1250.0                  231.0                  -1.0
256358            1323.0                  276.0                  -3.0
256373            1293.0                  227.0                  -9.0
256405            1321.0                  218.0                  -7.0
270742            1299.0                  344.0                  -5.0
270752            1256.0                  290.0                  -9.0
270762            1311.0                  323.0                  -2.0
276564            1368.0                  338.0                  -1.0
287148            1108.0                  211.0                  -3.0
291439             615.0                  198.0                  -2.0
305985             920.0                  203.0                  -3.0
325764             637.0                  221.0                  -4.0

[29 rows x 24 columns]

In [42]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
print(flights[(flights['dep_delay'] >= 30) & (flights['arr_delay'] >= 60)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
119     2013      1    1     811.0             630      101.0    1047.0
151     2013      1    1     848.0            1835      853.0    1001.0
218     2013      1    1     957.0             733      144.0    1056.0
268     2013      1    1    1114.0             900      134.0    1447.0
269     2013      1    1    1120.0             944       96.0    1331.0
...      ...    ...  ...       ...             ...        ...       ...
336664  2013      9   30    1943.0            1810       93.0    2140.0
336668  2013      9   30    1951.0            1649      182.0    2157.0
336724  2013      9   30    2053.0            1815      158.0    2310.0
336757  2013      9   30    2159.0            1845      194.0    2344.0
336763  2013      9   30    2235.0            2001      154.0      59.0

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
119                830      137.0      MQ  ...     118.0      544    6     30
151               1950      851.0      MQ  ...      41.0      184   18     35
218                853      123.0      UA  ...      37.0      200    7     33
268               1222      145.0      UA  ...     248.0     1416    9      0
269               1213       78.0      EV  ...     117.0      708    9     44
...                ...        ...     ...  ...       ...      ...  ...    ...
336664            1955      105.0      MQ  ...      72.0      479   18     10
336668            1903      174.0      EV  ...      95.0      708   16     49
336724            2054      136.0      EV  ...      91.0      746   18     15
336757            2030      194.0      9E  ...      50.0      301   18     45
336763            2249      130.0      B6  ...     123.0      944   20      1

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
119     2013-01-01T11:00:00Z             491.0                   390.0
151     2013-01-01T23:00:00Z             528.0                  1115.0
218     2013-01-01T12:00:00Z             597.0                   453.0
268     2013-01-01T14:00:00Z             674.0                   540.0
269     2013-01-01T14:00:00Z             680.0                   584.0
...                      ...               ...                     ...
336664  2013-09-30T22:00:00Z            1183.0                  1090.0
336668  2013-09-30T20:00:00Z            1191.0                  1009.0
336724  2013-09-30T22:00:00Z            1253.0                  1095.0
336757  2013-09-30T22:00:00Z            1319.0                  1125.0
336763  2013-10-01T00:00:00Z            1355.0                  1201.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
119                647.0                  156.0                 101.0
151                601.0                   73.0                -587.0
218                656.0                   59.0                 144.0
268                887.0                  213.0                 134.0
269                811.0                  131.0                  96.0
...                  ...                    ...                   ...
336664            1300.0                  117.0                  93.0
336668            1317.0                  126.0                 182.0
336724            1390.0                  137.0                 158.0
336757            1424.0                  105.0                 194.0
336763              59.0                -1296.0                 154.0

[26285 rows x 24 columns]

In [43]:
# Departed between midnight and 6am (inclusive)
print(flights[(flights['dep_time'] >= 0) & (flights['dep_time'] <= 600)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0
1       2013      1    1     533.0             529        4.0     850.0
2       2013      1    1     542.0             540        2.0     923.0
3       2013      1    1     544.0             545       -1.0    1004.0
4       2013      1    1     554.0             600       -6.0     812.0
...      ...    ...  ...       ...             ...        ...       ...
335802  2013      9   30     557.0             600       -3.0     852.0
335803  2013      9   30     558.0             600       -2.0     815.0
335804  2013      9   30     558.0             600       -2.0     742.0
335805  2013      9   30     559.0             600       -1.0       NaN
335806  2013      9   30     600.0             600        0.0     844.0

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
0                  819       11.0      UA  ...     227.0     1400    5     15
1                  830       20.0      UA  ...     227.0     1416    5     29
2                  850       33.0      AA  ...     160.0     1089    5     40
3                 1022      -18.0      B6  ...     183.0     1576    5     45
4                  837      -25.0      DL  ...     116.0      762    6      0
...                ...        ...     ...  ...       ...      ...  ...    ...
335802             923      -31.0      UA  ...     326.0     2586    6      0
335803             829      -14.0      EV  ...     107.0      746    6      0
335804             749       -7.0      DL  ...      83.0      502    6      0
335805             715        NaN      WN  ...       NaN      711    6      0
335806             856      -12.0      B6  ...     139.0     1069    6      0

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
0       2013-01-01T10:00:00Z             317.0                   315.0
1       2013-01-01T10:00:00Z             333.0                   329.0
2       2013-01-01T10:00:00Z             342.0                   340.0
3       2013-01-01T10:00:00Z             344.0                   345.0
4       2013-01-01T11:00:00Z             354.0                   360.0
...                      ...               ...                     ...
335802  2013-09-30T10:00:00Z             357.0                   360.0
335803  2013-09-30T10:00:00Z             358.0                   360.0
335804  2013-09-30T10:00:00Z             358.0                   360.0
335805  2013-09-30T10:00:00Z             359.0                   360.0
335806  2013-09-30T10:00:00Z             360.0                   360.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
0                  510.0                  193.0                   2.0
1                  530.0                  197.0                   4.0
2                  563.0                  221.0                   2.0
3                  604.0                  260.0                  -1.0
4                  492.0                  138.0                  -6.0
...                  ...                    ...                   ...
335802             532.0                  175.0                  -3.0
335803             495.0                  137.0                  -2.0
335804             462.0                  104.0                  -2.0
335805               NaN                    NaN                  -1.0
335806             524.0                  164.0                   0.0

[9344 rows x 24 columns]

In [44]:
# How many flights have a missing dep_time?
print(flights[flights['dep_time'].isnull()])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
838     2013      1    1       NaN            1630        NaN       NaN
839     2013      1    1       NaN            1935        NaN       NaN
840     2013      1    1       NaN            1500        NaN       NaN
841     2013      1    1       NaN             600        NaN       NaN
1777    2013      1    2       NaN            1540        NaN       NaN
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
838               1815        NaN      EV  ...       NaN      416   16     30
839               2240        NaN      AA  ...       NaN     1389   19     35
840               1825        NaN      AA  ...       NaN     1096   15      0
841                901        NaN      B6  ...       NaN     1069    6      0
1777              1747        NaN      EV  ...       NaN      569   15     40
...                ...        ...     ...  ...       ...      ...  ...    ...
336771            1634        NaN      9E  ...       NaN      213   14     55
336772            2312        NaN      9E  ...       NaN      198   22      0
336773            1330        NaN      MQ  ...       NaN      764   12     10
336774            1344        NaN      MQ  ...       NaN      419   11     59
336775            1020        NaN      MQ  ...       NaN      431    8     40

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
838     2013-01-01T21:00:00Z               NaN                   990.0
839     2013-01-02T00:00:00Z               NaN                  1175.0
840     2013-01-01T20:00:00Z               NaN                   900.0
841     2013-01-01T11:00:00Z               NaN                   360.0
1777    2013-01-02T20:00:00Z               NaN                   940.0
...                      ...               ...                     ...
336771  2013-09-30T18:00:00Z               NaN                   895.0
336772  2013-10-01T02:00:00Z               NaN                  1320.0
336773  2013-09-30T16:00:00Z               NaN                   730.0
336774  2013-09-30T15:00:00Z               NaN                   719.0
336775  2013-09-30T12:00:00Z               NaN                   520.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
838                  NaN                    NaN                   NaN
839                  NaN                    NaN                   NaN
840                  NaN                    NaN                   NaN
841                  NaN                    NaN                   NaN
1777                 NaN                    NaN                   NaN
...                  ...                    ...                   ...
336771               NaN                    NaN                   NaN
336772               NaN                    NaN                   NaN
336773               NaN                    NaN                   NaN
336774               NaN                    NaN                   NaN
336775               NaN                    NaN                   NaN

[8255 rows x 24 columns]

## Question 2. Sorting

In [45]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
print(flights.sort_values(by='dep_delay'))
print(flights.sort_values(by='dep_time'))

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
89673   2013     12    7    2040.0            2123      -43.0      40.0
113633  2013      2    3    2022.0            2055      -33.0    2240.0
64501   2013     11   10    1408.0            1440      -32.0    1549.0
9619    2013      1   11    1900.0            1930      -30.0    2233.0
24915   2013      1   29    1703.0            1730      -27.0    1947.0
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
89673             2352       48.0      B6  ...     265.0     1626   21     23
113633            2338      -58.0      DL  ...     162.0     1183   20     55
64501             1559      -10.0      EV  ...      52.0      229   14     40
9619              2243      -10.0      DL  ...     139.0     1010   19     30
24915             1957      -10.0      F9  ...     250.0     1620   17     30
...                ...        ...     ...  ...       ...      ...  ...    ...
336771            1634        NaN      9E  ...       NaN      213   14     55
336772            2312        NaN      9E  ...       NaN      198   22      0
336773            1330        NaN      MQ  ...       NaN      764   12     10
336774            1344        NaN      MQ  ...       NaN      419   11     59
336775            1020        NaN      MQ  ...       NaN      431    8     40

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
89673   2013-12-08T02:00:00Z            1240.0                  1283.0
113633  2013-02-04T01:00:00Z            1222.0                  1255.0
64501   2013-11-10T19:00:00Z             848.0                   880.0
9619    2013-01-12T00:00:00Z            1140.0                  1170.0
24915   2013-01-29T22:00:00Z            1023.0                  1050.0
...                      ...               ...                     ...
336771  2013-09-30T18:00:00Z               NaN                   895.0
336772  2013-10-01T02:00:00Z               NaN                  1320.0
336773  2013-09-30T16:00:00Z               NaN                   730.0
336774  2013-09-30T15:00:00Z               NaN                   719.0
336775  2013-09-30T12:00:00Z               NaN                   520.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
89673               40.0                -1200.0                 -43.0
113633            1360.0                  138.0                 -33.0
64501              949.0                  101.0                 -32.0
9619              1353.0                  213.0                 -30.0
24915             1187.0                  164.0                 -27.0
...                  ...                    ...                   ...
336771               NaN                    NaN                   NaN
336772               NaN                    NaN                   NaN
336773               NaN                    NaN                   NaN
336774               NaN                    NaN                   NaN
336775               NaN                    NaN                   NaN

[336776 rows x 24 columns]
        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
10452   2013      1   13       1.0            2249       72.0     108.0
100800  2013     12   20       1.0            2359        2.0     430.0
212954  2013      5   22       1.0            1935      266.0     154.0
297030  2013      8   19       1.0            2359        2.0     347.0
131559  2013      2   24       1.0            2245       76.0     121.0
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
10452             2357       71.0      B6  ...      41.0      209   22     49
100800             440      -10.0      B6  ...     182.0     1598   23     59
212954            2140      254.0      EV  ...      94.0      631   19     35
297030             350       -3.0      B6  ...     201.0     1617   23     59
131559            2354       87.0      B6  ...      56.0      273   22     45
...                ...        ...     ...  ...       ...      ...  ...    ...
336771            1634        NaN      9E  ...       NaN      213   14     55
336772            2312        NaN      9E  ...       NaN      198   22      0
336773            1330        NaN      MQ  ...       NaN      764   12     10
336774            1344        NaN      MQ  ...       NaN      419   11     59
336775            1020        NaN      MQ  ...       NaN      431    8     40

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
10452   2013-01-14T03:00:00Z               1.0                  1369.0
100800  2013-12-21T04:00:00Z               1.0                  1439.0
212954  2013-05-22T23:00:00Z               1.0                  1175.0
297030  2013-08-20T03:00:00Z               1.0                  1439.0
131559  2013-02-25T03:00:00Z               1.0                  1365.0
...                      ...               ...                     ...
336771  2013-09-30T18:00:00Z               NaN                   895.0
336772  2013-10-01T02:00:00Z               NaN                  1320.0
336773  2013-09-30T16:00:00Z               NaN                   730.0
336774  2013-09-30T15:00:00Z               NaN                   719.0
336775  2013-09-30T12:00:00Z               NaN                   520.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
10452               68.0                   67.0               -1368.0
100800             270.0                  269.0               -1438.0
212954             114.0                  113.0               -1174.0
297030             227.0                  226.0               -1438.0
131559              81.0                   80.0               -1364.0
...                  ...                    ...                   ...
336771               NaN                    NaN                   NaN
336772               NaN                    NaN                   NaN
336773               NaN                    NaN                   NaN
336774               NaN                    NaN                   NaN
336775               NaN                    NaN                   NaN

[336776 rows x 24 columns]

In [46]:
# Which flights travelled the farthest? Which travelled the shortest?
print(flights.sort_values(by='distance', ascending=False))

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
118311  2013      2    9    1206.0             900      186.0    1814.0
227103  2013      6    6    1044.0            1000       44.0    1441.0
224146  2013      6    3     957.0            1000       -3.0    1432.0
170226  2013      4    6     957.0            1000       -3.0    1510.0
130088  2013      2   22     857.0             900       -3.0    1436.0
...      ...    ...  ...       ...             ...        ...       ...
115505  2013      2    5    2136.0            2130        6.0    2238.0
25145   2013      1   29    2131.0            2130        1.0    2221.0
170692  2013      4    6    1948.0            1950       -2.0    2034.0
112694  2013      2    2    1610.0            1617       -7.0    1702.0
275945  2013      7   27       NaN             106        NaN       NaN

        sched_arr_time  arr_delay carrier  ...  air_time distance hour minute  \
118311            1540      154.0      HA  ...     645.0     4983    9      0
227103            1435        6.0      HA  ...     580.0     4983   10      0
224146            1435       -3.0      HA  ...     605.0     4983   10      0
170226            1510        0.0      HA  ...     638.0     4983   10      0
130088            1540      -64.0      HA  ...     606.0     4983    9      0
...                ...        ...     ...  ...       ...      ...  ...    ...
115505            2225       13.0      EV  ...      31.0       80   21     30
25145             2225       -4.0      EV  ...      25.0       80   21     30
170692            2044      -10.0      EV  ...      25.0       80   19     50
112694            1722      -20.0      EV  ...      33.0       80   16     17
275945             245        NaN      US  ...       NaN       17    1      6

                   time_hour  dep_time_minutes  sched_dep_time_minutes  \
118311  2013-02-09T14:00:00Z             726.0                   540.0
227103  2013-06-06T14:00:00Z             644.0                   600.0
224146  2013-06-03T14:00:00Z             597.0                   600.0
170226  2013-04-06T14:00:00Z             597.0                   600.0
130088  2013-02-22T14:00:00Z             537.0                   540.0
...                      ...               ...                     ...
115505  2013-02-06T02:00:00Z            1296.0                  1290.0
25145   2013-01-30T02:00:00Z            1291.0                  1290.0
170692  2013-04-06T23:00:00Z            1188.0                  1190.0
112694  2013-02-02T21:00:00Z             970.0                   977.0
275945  2013-07-27T05:00:00Z               NaN                    66.0

        arr_time_minutes calculated_flight_time  calculated_dep_delay
118311            1094.0                  368.0                 186.0
227103             881.0                  237.0                  44.0
224146             872.0                  275.0                  -3.0
170226             910.0                  313.0                  -3.0
130088             876.0                  339.0                  -3.0
...                  ...                    ...                   ...
115505            1358.0                   62.0                   6.0
25145             1341.0                   50.0                   1.0
170692            1234.0                   46.0                  -2.0
112694            1022.0                   52.0                  -7.0
275945               NaN                    NaN                   NaN

[336776 rows x 24 columns]

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [47]:
print(flights[['dep_time', 'dep_delay', 'arr_time', 'arr_delay']])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [48]:
print(flights.loc[:, ['dep_time', 'dep_delay', 'arr_time', 'arr_delay']])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [49]:
print(flights.iloc[:, [3, 5, 6, 8]])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [50]:
# Convert dep_time and sched_dep_time to minutes since midnight
import numpy as np

dep_time_notna = flights['dep_time'].notna()
sched_dep_time_notna = flights['sched_dep_time'].notna()

flights['dep_time_minutes'] = np.nan
flights['sched_dep_time_minutes'] = np.nan

flights.loc[dep_time_notna, 'dep_time_minutes'] = \
    (flights.loc[dep_time_notna, 'dep_time'].astype(int).astype(str).str.zfill(4).str[0:2].astype(float) * 60) + \
    (flights.loc[dep_time_notna, 'dep_time'].astype(int).astype(str).str.zfill(4).str[2:4].astype(float))

flights.loc[sched_dep_time_notna, 'sched_dep_time_minutes'] = \
    (flights.loc[sched_dep_time_notna, 'sched_dep_time'].astype(int).astype(str).str.zfill(4).str[0:2].astype(float) * 60) + \
    (flights.loc[sched_dep_time_notna, 'sched_dep_time'].astype(int).astype(str).str.zfill(4).str[2:4].astype(float))

print(flights[['dep_time', 'dep_time_minutes', 'sched_dep_time', 'sched_dep_time_minutes']].head())

   dep_time  dep_time_minutes  sched_dep_time  sched_dep_time_minutes
0     517.0             317.0             515                   315.0
1     533.0             333.0             529                   329.0
2     542.0             342.0             540                   340.0
3     544.0             344.0             545                   345.0
4     554.0             354.0             600                   360.0

In [51]:
# Create a new column of arr_time - dep_time.
import numpy as np

arr_time_notna = flights['arr_time'].notna()
flights['arr_time_minutes'] = np.nan
flights.loc[arr_time_notna, 'arr_time_minutes'] = \
    (flights.loc[arr_time_notna, 'arr_time'].astype(int).astype(str).str.zfill(4).str[0:2].astype(float) * 60) + \
    (flights.loc[arr_time_notna, 'arr_time'].astype(int).astype(str).str.zfill(4).str[2:4].astype(float))

flights['calculated_flight_time'] = flights['arr_time_minutes'] - flights['dep_time_minutes']

# Compare this column with air_time.
print(flights[['air_time', 'calculated_flight_time']].head())
print("\nMean difference (air_time - calculated_flight_time):")
print((flights['air_time'] - flights['calculated_flight_time']).mean())

   air_time  calculated_flight_time
0     227.0                   193.0
1     227.0                   197.0
2     160.0                   221.0
3     183.0                   260.0
4     116.0                   138.0

Mean difference (air_time - calculated_flight_time):
59.730221233801544

In [52]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).
flights['calculated_dep_delay'] = flights['dep_time_minutes'] - flights['sched_dep_time_minutes']

# Test your results.
print(flights[['dep_delay', 'calculated_dep_delay']].head())
print("\nMean difference (dep_delay - calculated_dep_delay):")
print((flights['dep_delay'] - flights['calculated_dep_delay']).mean())
print("\nNumber of mismatches:")
print((flights['dep_delay'] != flights['calculated_dep_delay']).sum())

   dep_delay  calculated_dep_delay
0        2.0                   2.0
1        4.0                   4.0
2        2.0                   2.0
3       -1.0                  -1.0
4       -6.0                  -6.0

Mean difference (dep_delay - calculated_dep_delay):
5.290620690914736

Number of mismatches:
9462

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [53]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay,carrier
# How do you want to handle ties?
most_delayed_flights = flights.sort_values(by='dep_delay', ascending=False).head(20)
print(most_delayed_flights[['year', 'month', 'day', 'carrier', 'flight', 'dep_delay', 'arr_delay']])

        year  month  day carrier  flight  dep_delay  arr_delay
7072    2013      1    9      HA      51     1301.0     1272.0
235778  2013      6   15      MQ    3535     1137.0     1127.0
8239    2013      1   10      MQ    3695     1126.0     1109.0
327043  2013      9   20      AA     177     1014.0     1007.0
270376  2013      7   22      MQ    3075     1005.0      989.0
173992  2013      4   10      DL    2391      960.0      931.0
151974  2013      3   17      DL    2119      911.0      915.0
247040  2013      6   27      DL    2007      899.0      850.0
270987  2013      7   22      DL    2047      898.0      895.0
87238   2013     12    5      AA     172      896.0      878.0
195711  2013      5    3      MQ    3744      878.0      875.0
151     2013      1    1      MQ    3944      853.0      851.0
210174  2013      5   19      AA     257      853.0      852.0
119784  2013      2   10      F9     835      853.0      834.0
99938   2013     12   19      DL    1223      849.0      847.0
98014   2013     12   17      AA     172      845.0      846.0
95530   2013     12   14      DL    2391      825.0      856.0
182478  2013      4   19      DL    1435      812.0      821.0
246911  2013      6   27      AA    2019      803.0      802.0
152312  2013      3   18      DL    2363      800.0      784.0

In [54]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,orig,dest,distance,air_time,speed (miles per hour)

aa_flights = flights[flights['carrier'] == 'AA'].copy()
aa_flights['speed'] = aa_flights['distance'] / (aa_flights['air_time'] / 60)
fastest_aa_flights = aa_flights.sort_values(by='speed', ascending=False).head(10)
print(fastest_aa_flights[['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']])

        year  month  day carrier  flight origin dest  distance  air_time  \
70704   2013     11   17      AA     936    JFK  STT      1623     175.0
87723   2013     12    5      AA    1029    JFK  SJU      1598     173.0
119700  2013      2   10      AA    1613    JFK  SJU      1598     173.0
129686  2013      2   21      AA    1613    JFK  SJU      1598     174.0
87575   2013     12    5      AA      95    JFK  SJU      1598     175.0
144408  2013      3    9      AA    1613    JFK  SJU      1598     176.0
70721   2013     11   17      AA    1357    JFK  SJU      1598     176.0
70335   2013     11   16      AA      95    JFK  SJU      1598     177.0
119477  2013      2   10      AA    1635    JFK  SJU      1598     177.0
119894  2013      2   11      AA     413    JFK  SJU      1598     177.0

             speed
70704   556.457143
87723   554.219653
119700  554.219653
129686  551.034483
87575   547.885714
144408  544.772727
70721   544.772727
70335   541.694915
119477  541.694915
119894  541.694915

In [55]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time

filtered_flights = flights[
    ((flights['origin'] == 'JFK') | (flights['origin'] == 'EWR')) &
    (flights['dest'] == 'SEA') &
    ((flights['carrier'] == 'UA') | (flights['carrier'] == 'AA') | (flights['carrier'] == 'DL')) &
    (flights['month'] == 4) & (flights['day'] >= 1) & (flights['day'] <= 3) &
    (flights['sched_arr_time'] < 1200)
]

sorted_flights = filtered_flights.sort_values(by=['year', 'month', 'day', 'sched_arr_time'])

print(sorted_flights[['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'sched_dep_time', 'sched_arr_time']])

        year  month  day carrier  flight origin dest  sched_dep_time  \
165210  2013      4    1      DL     183    JFK  SEA             745
166180  2013      4    2      DL     183    JFK  SEA             745
167168  2013      4    3      DL     183    JFK  SEA             745

        sched_arr_time
165210            1100
166180            1100
167168            1100